Add java sample
Azure-Samples/msal-managed-identity pull request #12
Opened 2024-03-14 22:13 UTC by neha-bhargava

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2024-03-18 13:36 UTC, bgavrilMS approved these changes, later dismissed

2024-03-18 19:36 UTC, Avery-Dunn approved these changes, later dismissed

2024-03-19 00:04 UTC, localden requested changes

2024-03-19 00:04 UTC, localden commented on src/java/readme.md
> +This sample showcases how to acquire a secret from an Azure Key Vault using Azure Managed Identity. It shows you how to use the managed identity for [Azure functions](https://learn.microsoft.com/en-u
```suggestion
This sample showcases how to acquire a secret from an Azure Key Vault using Azure Managed Identity. It shows you how to use the managed identity for [Azure Functions](https://learn.microsoft.com/azure/azure-functions/functions-overview?pivots=programming-language-java) and acquire a token for an Azure Key Vault resource.
```

2024-03-19 00:04 UTC, localden commented on src/java/readme.md
> +For more information about how the protocols work in this scenario and other scenarios, see [Authentication Scenarios for Azure AD](http://go.microsoft.com/fwlink/?LinkId=394414).
```suggestion
For more information about how the protocols work in this scenario and other scenarios, see [Authentication Scenarios for Microsoft Entra ID](http://go.microsoft.com/fwlink/?LinkId=394414).
```

2024-03-19 00:04 UTC, localden commented on src/java/readme.md
> +[Deploy your function](https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-maven-intellij#deploy-your-project-to-azure) using IntelliJ
```suggestion
[Deploy your function](https://learn.microsoft.com/azure/azure-functions/functions-create-maven-intellij#deploy-your-project-to-azure) using IntelliJ
```

2024-03-19 00:04 UTC, localden commented on src/java/readme.md
> +- [Enable the System Assigned managed identity](https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-access-azure-sql-with-managed-identity#enable-system-assigned-managed-identi
```suggestion
- [Enable the System Assigned managed identity](https://learn.microsoft.com/azure/azure-functions/functions-identity-access-azure-sql-with-managed-identity#enable-system-assigned-managed-identity-on-azure-function) of the resource.
```

2024-03-19 00:04 UTC, localden commented on src/java/readme.md
> +To launch the function you can use the following:
```suggestion
To launch the function you can use the following:

```

2024-03-19 00:04 UTC, localden commented on src/java/readme.md
> +This error indicates that the managed identity endpoint is not reachable. Please refer to [how to enable managed identity on Azure functions](https://learn.microsoft.com/en-us/azure/azure-functions/f
```suggestion
This error indicates that the managed identity endpoint is not reachable. Please refer to [how to enable managed identity on Azure functions](https://learn.microsoft.com/azure/azure-functions/functions-identity-access-azure-sql-with-managed-identity#enable-system-assigned-managed-identity-on-azure-function)
```

2024-03-21 05:44 UTC, merged